### PR TITLE
Fix: Use values only

### LINKED ISSUE #100: Malformed payload
We've received a report of a user struggling to set up php test coverage, and with their permission, took a look at the payload being sent by the php-test-reporter. Here's a little node.js script showing some characteristics of the payload we're receiving:

```javascript
var fs = require('fs');
var data = JSON.parse(fs.readFileSync("./payload.json", "utf8"));

console.log(typeof data.coverage_data.source_files);
// object

console.log(Object.keys(data.coverage_data.source_files).slice(0, 2));
//[ '/opt/atlassian/pipelines/agent/build/src/Api.php',
//  '/opt/atlassian/pipelines/agent/build/src/ApiHandler.php' ]

console.log(data.coverage_data.source_files['/opt/atlassian/pipelines/agent/build/src/Api.php']);
// { name: 'src/Api.php',
//  coverage: '[null,null,null,null,null,null,null,null,null,null,null,null]',
//  blob_id: 'f4d95e0cb279952a0569e6f734cb0a2bc22ad864' }
```

You can see that `data.coverage_data.source_files` is an object, but that's malformed -- it should be an array. We don't need the keys in that object at all, we just want the values.

I'm not sure why this is happening, or if it's affecting many users or just this one. Is it possible that a user is getting different dependency versions or using a different version of php, and that could lead to this issue?

It looks like this repo doesn't have very many tests, so I think we ought to add some that exercise the format of the payload, to help smoke out if there is a bug there.

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] removes the keys when generating the payload

Follows #76.
Fixes #100.

💁‍♂️ My bad, thanks a ton for digging into it, @maxjacobson! I will make sure to add tests later, too.

### CODE REVIEW

**Comment by maxjacobson** [comment]
Hey @localheinz thanks for looking into this!

Did some playing around in a php playground to confirm that this looks like it'll do the right thing: https://www.tehplayground.com/zbTW7R0p3HD408nB

Some real tests would be better but for now I'm satisfied :)

**Comment by localheinz** [comment]
Thank you, @maxjacobson!

**Comment by localheinz** [comment]
Let's tag this, too, what do you think?

This will help at least all the folks who have required the latest version, or use the `^` operator (despite the fact that it is an unstable package)!

**Comment by maxjacobson** [comment]
@localheinz I'm open to it, but think we have some more work to do with our release process. Are you pulling in the test reporter at a specific tag when you use it? I sort of think everyone is just pulling in the latest master.

Some context: #54 isn't closed yet. #61 was merged, but we haven't perfectly adopted its recommendations - note that [our releases](https://github.com/codeclimate/php-test-reporter/releases) don't include any downloads.

**Comment by localheinz** [comment]
@maxjacobson 

According to http://semver.org/#spec-item-4

> Major version zero (`0.y.z`) is for initial development. Anything may change at any time. The public API should not be considered stable.

I never require unstable dependencies using the `^` or any other wildcard operators - I always pin to a concrete version.

**Comment by maxjacobson** [comment]
Yup, good call. Tagging 0.4.2 today https://github.com/codeclimate/php-test-reporter/pull/102

**Pull request merged**
