### PR TITLE
Fix composer branch alias

### PR DESCRIPTION
**Pull request by Soullivaneuh**

### CODE REVIEW

**Comment by GordonDiggs** [comment]
@Soullivaneuh can you explain this change? AFAIK, we have switched entirely to [using Packagist](https://packagist.org/packages/codeclimate/php-test-reporter) and left that line for legacy support

**Comment by Soullivaneuh** [comment]
You're maintaining master and pushed 0.2. But composer will don't understand if somebody require `0.2.*@dev` for example.

If you want simplier one, you can set `0.x-dev` instead.

> we have switched entirely to using Packagist and left that line for legacy support

Packagist **uses** branch aliases.

Ping @Seldaek for clearer explanations. :-)

**Comment by Seldaek** [comment]
Ping the docs for explanations, I'm not a friggin hotline https://getcomposer.org/doc/articles/aliases.md

**Comment by GordonDiggs** [comment]
@Soullivaneuh @Seldaek thanks! I'm not super familiar with the way composer works, so wasn't clear on the full process.

**Comment by Soullivaneuh** [comment]
Sorry for disturbing @Seldaek, it was not an obligation to answer. It's just a ping in cas you got some time for it.

Anyway, thanks for the answer.

**Pull request merged**
