### PR TITLE
Added cURL backup method to ApiClient

### PR DESCRIPTION
**Pull request by aensley**
Attempting to solve the following error in Travis-CI builds with [`allow_url_fopen`](https://secure.php.net/manual/en/filesystem.configuration.php#ini.allow-url-fopen) disabled:

```
Unexpected response: 500 fopen(https://codeclimate.com/test_reports): failed to open stream: no suitable wrapper could be found
```

Example project and build log:
https://github.com/aensley/YahooStockQuotes
https://travis-ci.org/aensley/YahooStockQuotes/jobs/123515259#L314

### CODE REVIEW

**Comment by jpignata** [comment]
@aensley A couple of random (probably dumb – sorry 😄 ) questions:

1. Is it possible for us to toggle this runtime configuration in our test reporter for the duration of the send if it's disabled?
2. If not, would it perhaps be better if we always used libcurl?

**Comment by aensley** [comment]
Not dumb at all.

 1. I'm not sure in this specific case. Many (most?) variables can be changed with [`ini_set()`](https://secure.php.net/manual/en/function.ini-set.php), but not all.
 2. It might be better to default to cURL and fallback to PHP Streams. If the user does not have cURL installed, obviously, they'll need the fallback. I've never seen anyone complain about not having cURL but lots have complained about not having code that uses it :-p.

Since I was adding an alternative, I kept the current/previous method as the default. I can change this if you think it would be better.

**Comment by aensley** [comment]
I could see it not being possible to change this at run-time. It's a security-related option, so I doubt it could be changed at runtime. Safe Mode also disables allow_url_fopen, and I'm certain it can't be changed in that situation.

**Comment by jpignata** [comment]
@aensley Makes sense. Thanks!

**Comment by aensley** [comment]
Awesome. Thanks!

**Comment by aensley** [comment]
It worked!

https://travis-ci.org/aensley/YahooStockQuotes/jobs/124034663#L412

**Comment by aensley** [comment]
You might want to remove this line to reduce output:

```PHP
curl_setopt($curl, CURLOPT_VERBOSE, true);
```

I forgot to take that out. Sorry.

**Pull request merged**
