### PR TITLE
Fix: Simplify regular expression

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] simplifies a regular expression

### CODE REVIEW

**Comment by pbrisbin** [comment]
This looks good, please rebase and resolve and I'll merge.

**Comment by localheinz** [comment]
@pbrisbin 

Rebased!

**Comment by pbrisbin** [comment]
Thanks for all the fixes, and for doing them as distinct commits/PRs!

**Comment by localheinz** [comment]
@pbrisbin 

This is how we roll, hehe! Thanks a lot for reviewing!

**Pull request merged**
