### PR TITLE
Add missing semi colon

### PR DESCRIPTION
**Pull request by ABaldwinHunter**
Thinking this might fix https://github.com/codeclimate/php-test-reporter/issues/107

cc @localheinz let me know what you think!

### CODE REVIEW

**Comment by maxjacobson** [comment]
This LGTM - surprised it wasn't caught by a linter. Maybe because no php file extension?

**Comment by ABaldwinHunter** [comment]
@maxjacobson yeah, idk. I experimented with changing the file extension and running CLI php engines but didn't see that issue come up.

If this missing semi colon is the culprit, we probably want a test that would have caught an error here. I should add that now but might in a separate PR.

**Comment by ABaldwinHunter** [comment]
Looks like our travis script also errored before but the build was green because exit code was 0: https://travis-ci.org/codeclimate/php-test-reporter/jobs/194909344#L263

good find @maxjacobson

**Comment by localheinz** [comment]
Ha, my bad, thank you @ABaldwinHunter!

**Comment by localheinz** [comment]
Related to #104.

**Pull request merged**
