### PR TITLE
Remove coveralls requirement

### PR DESCRIPTION
**Pull request by enygma**
This pull request removes the requirement on the Coveralls library to create the JSON payload needed by the Code Climate API for reporting coverage information.

### CODE REVIEW

**Comment by JacobNinja** [comment]
Hey Chris thanks for removing the dependency. Would you mind adding some tests covering the XML->JSON transformation? I'm thinking a high level test with the XML input and JSON output would be ideal.

**Comment by enygma** [comment]
Will do - sorry for the delay on this!

**Comment by noahd1** [comment]
Friendly ping :)

**Comment by jpignata** [comment]
Closing due to staleness.

**Pull request closed without merging**
