### PR TITLE
Few improvements on GIT binary and travis 

### PR DESCRIPTION
**Pull request by renatomefidf**
Now the binary is testing the git and giving a message on failure.
Travis is now updating composer and I removed the --dev deprecated argument;
Travis is testing PHP 5.4 to 5.6

https://travis-ci.org/renatomefidf/php-test-reporter/builds/54754831

### CODE REVIEW

**Comment by renatomefidf** [comment]
Just added new features! :)

**Comment by renatomefidf** [comment]
Ping @JacobNinja

**Comment by renatomefidf** [comment]
Hello @jonathancadepowers, is there something missing in my PR? Since I didn't have any feedback I would like to know if I can improve it in someway.

Thank you!

**Comment by jpignata** [comment]
Closing due to staleness.

**Comment by renatomefidf** [comment]
Code climate is doing a bad job in managing community!
I'll probably not contribute to it anymore.

@jpignata at least thanks for making clear Code Climate doesn't care about contributions!

**Pull request closed without merging**
