### PR TITLE
Enhancement: Extract GitInfo value object

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] extracts a `GitInfo` value object

Related to #119.

💁‍♂️ The idea would be to not let `JsonFile` use the `GitCommand` to fetch this information, but inject it instead.

### CODE REVIEW

**Comment by localheinz** [comment]
@maxjacobson 

Sure!

This PR is related to #119 insofar as that the aim is to 

* untangle the existing classes
* inject dependencies instead of creating them within in order to make everything testable
* cover existing code with tests

What do you think?

**Comment by maxjacobson** [comment]
Yep, I think this looks good. Feel free to merge 👍

**Comment by localheinz** [comment]
Thank you, @maxjacobson!

**Comment by maxjacobson** [comment]
@localheinz as usual, thank _you_ for all your help. I always learn a bit more about PHP from reviewing your PRs 😄

**Comment by localheinz** [comment]
Ha, no worries, there will be more, @maxjacobson!

**Pull request merged**
