### PR TITLE
Removed obsolete root dir in stub, Application and TestReporterCommand

### PR DESCRIPTION
**Pull request by hollodotme**
Based on #55, related to #54.

### CODE REVIEW

**Comment by pbrisbin** [comment]
Hello. Now that #58 merged, can you rebase this so I can review it? Then we can do the same for #57 after this merged. Thanks!

**Comment by hollodotme** [comment]
@pbrisbin rebased the PR branch. You should be able to merge now.

**Comment by pbrisbin** [comment]
Hmm. I'm not really sure how this PR would cause this, but it seems to have had trouble posting test coverage: https://travis-ci.org/codeclimate/php-test-reporter/builds/148437975#L276

Any ideas? I've confirmed in Travis settings that that environment variable is configured, and it worked on the other branches.

**Comment by hollodotme** [comment]
Sorry, I don't fully understand the issue. Can you please explain it in more detail?

**Comment by pbrisbin** [comment]
All I really know at this point is the linked stack trace:

```
PHP Notice:  Undefined index: CODECLIMATE_REPO_TOKEN in /home/travis/build/codeclimate/php-test-reporter/src/TestReporter/Entity/JsonFile.php on line 31
PHP Stack trace:
PHP   1. {main}() /home/travis/build/codeclimate/php-test-reporter/composer/bin/test-reporter:0
PHP   2. Symfony\Component\Console\Application->run() /home/travis/build/codeclimate/php-test-reporter/composer/bin/test-reporter:32
PHP   3. Symfony\Component\Console\Application->doRun() /home/travis/build/codeclimate/php-test-reporter/vendor/symfony/console/Application.php:123
PHP   4. Symfony\Component\Console\Application->doRunCommand() /home/travis/build/codeclimate/php-test-reporter/vendor/symfony/console/Application.php:192
PHP   5. Symfony\Component\Console\Command\Command->run() /home/travis/build/codeclimate/php-test-reporter/vendor/symfony/console/Application.php:844
PHP   6. CodeClimate\PhpTestReporter\ConsoleCommands\TestReporterCommand->execute() /home/travis/build/codeclimate/php-test-reporter/vendor/symfony/console/Command/Command.php:259
PHP   7. CodeClimate\PhpTestReporter\TestReporter\ApiClient->send() /home/travis/build/codeclimate/php-test-reporter/src/ConsoleCommands/TestReporterCommand.php:55
PHP   8. Satooshi\Bundle\CoverallsV1Bundle\Entity\Coveralls->__toString() /home/travis/build/codeclimate/php-test-reporter/src/ConsoleCommands/TestReporterCommand.php:32
PHP   9. CodeClimate\PhpTestReporter\TestReporter\Entity\JsonFile->toArray() /home/travis/build/codeclimate/php-test-reporter/vendor/satooshi/php-coveralls/src/Satooshi/Bundle/CoverallsV1Bundle/Entity/Coveralls.php:21
PHP  10. CodeClimate\PhpTestReporter\TestReporter\Entity\JsonFile->getRepoToken() /home/travis/build/codeclimate/php-test-reporter/src/TestReporter/Entity/JsonFile.php:16
Notice: Undefined index: CODECLIMATE_REPO_TOKEN in /home/travis/build/codeclimate/php-test-reporter/src/TestReporter/Entity/JsonFile.php on line 31
Call Stack:
    0.0002     240304   1. {main}() /home/travis/build/codeclimate/php-test-reporter/composer/bin/test-reporter:0
    0.0126    2090816   2. Symfony\Component\Console\Application->run() /home/travis/build/codeclimate/php-test-reporter/composer/bin/test-reporter:32
    0.0158    2524192   3. Symfony\Component\Console\Application->doRun() /home/travis/build/codeclimate/php-test-reporter/vendor/symfony/console/Application.php:123
    0.0159    2525144   4. Symfony\Component\Console\Application->doRunCommand() /home/travis/build/codeclimate/php-test-reporter/vendor/symfony/console/Application.php:192
    0.0159    2525672   5. Symfony\Component\Console\Command\Command->run() /home/travis/build/codeclimate/php-test-reporter/vendor/symfony/console/Application.php:844
    0.0161    2528104   6. CodeClimate\PhpTestReporter\ConsoleCommands\TestReporterCommand->execute() /home/travis/build/codeclimate/php-test-reporter/vendor/symfony/console/Command/Command.php:259
    0.0224    2935568   7. CodeClimate\PhpTestReporter\TestReporter\ApiClient->send() /home/travis/build/codeclimate/php-test-reporter/src/ConsoleCommands/TestReporterCommand.php:55
    0.0224    2935704   8. Satooshi\Bundle\CoverallsV1Bundle\Entity\Coveralls->__toString() /home/travis/build/codeclimate/php-test-reporter/src/ConsoleCommands/TestReporterCommand.php:32
    0.0224    2935824   9. CodeClimate\PhpTestReporter\TestReporter\Entity\JsonFile->toArray() /home/travis/build/codeclimate/php-test-reporter/vendor/satooshi/php-coveralls/src/Satooshi/Bundle/CoverallsV1Bundle/Entity/Coveralls.php:21
    0.0224    2936336  10. CodeClimate\PhpTestReporter\TestReporter\Entity\JsonFile->getRepoToken() /home/travis/build/codeclimate/php-test-reporter/src/TestReporter/Entity/JsonFile.php:16
```

**Comment by pbrisbin** [comment]
I guess it looks like the Travis build just didn't expose the environment variable for some reason. I'll try a rebuild and see what happens.

**Comment by pbrisbin** [comment]
Ah I know. I always forget about this. CI systems don't expose project environment variables to outside contributor PRs for security reasons.

**Pull request merged**
